### ISSUE TITLE
Document the monitoring puppet module 

### ISSUE THREAD

**Issue by tophertimzen** [redteaminfra/redteam-infra#30]
https://github.com/redteaminfra/redteam-infra/tree/master/puppet/modules/monitoring is not documented in the module README

**Comment by tophertimzen** [comment]
Needs to include what to put in config such as

```
filter:
- query:
    query_string:
      query: "host: proxy* AND \"200\" AND NOT \"/s/ref\" AND (client: [IP TO IP]  OR client: [IP TO IP] )"
```

to demonstrate how to fill these files in
